### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by ghost** [mai1zhi2/SharpBeacon#1]
i have got everything complied, and I wonder how to use it ?? is there any cna script?
can you provide help ? thx

**Comment by bopin2020** [comment]
Firstly, starting TeamServer and you got .cobaltstrike.beacon_keys meanwhile configurate listener etc.
Secondly, compiling SharpBeacon with VisualStudio after you changed url and RSA private key and public key in config.cs
And Then click sharpbeacon.exe. Once you got one beacon session and have fun!
BTW this project as just a beacon which depends on CobaltStrike.

**Comment by mai1zhi2** [comment]
Thanks bopin2020
